# Generated by Django 5.2.6 on 2025-09-25 10:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید دقیقاً 10 رقم باشد', regex='^\\d{10}$')], verbose_name='کد ملی')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با 09 شروع شود و 11 رقم باشد', regex='^09\\d{9}$')], verbose_name='شماره موبایل')),
                ('wallet_balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='موجودی کیف پول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('customer_create', 'ثبت مشتری'), ('customer_edit', 'ویرایش مشتری'), ('purchase_create', 'ثبت خرید'), ('user_login', 'ورود به سیستم'), ('user_logout', 'خروج از سیستم')], max_length=20, verbose_name='نوع فعالیت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش فعالیت',
                'verbose_name_plural': 'گزارش فعالیت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ خرید')),
                ('cashback_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ کش\u200cبک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='cashback_app.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'خرید',
                'verbose_name_plural': 'خریدها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'مدیر'), ('operator', 'اپراتور')], default='operator', max_length=10, verbose_name='نوع کاربر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
    ]
