# Generated by Django 4.2.7 on 2025-10-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashback_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashback_app.customer', verbose_name='مشتری مرتبط'),
        ),
    ]
